/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.turn.java-conventions")
}

dependencies {
    api(project(":ttorrent-common"))
    api(project(":ttorrent-bencoding"))
    testImplementation(project(":ttorrent-test-api"))
}

description = "ttorrent/tracker"
