/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.turn.java-conventions")
}

dependencies {
    api(project(":ttorrent-client"))
    api(project(":ttorrent-tracker"))
    api("net.sf:jargs:1.0")
}

description = "Java BitTorrent library CLI"
