/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.turn.java-conventions")
}

dependencies {
    api("org.mockito:mockito-core:5.8.0")
    api("commons-io:commons-io:2.15.1")
    api("commons-codec:commons-codec:1.16.0")
    api("org.simpleframework:simple:5.1")
    api("org.jetbrains:annotations-java5:24.0.1")
    api("org.slf4j:slf4j-api:2.0.9")
    testImplementation("org.testng:testng:7.9.0")
    api(project(":ttorrent-bencoding"))
}

description = "ttorrent/common"
repositories {
    mavenCentral()
}
